coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
      backend:
        flags:
          - backend
        target: 80%
        threshold: 2%
      frontend:
        flags:
          - frontend
        target: 70%
        threshold: 2%
    patch:
      default:
        target: 70%
        threshold: 2%

flags:
  backend:
    paths:
      - src/
  frontend:
    paths:
      - frontend/src/

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - main
    - dev

ignore:
  - "frontend/coverage/**"
  - "frontend/dist/**"
  - "frontend/build/**"
  - "frontend/node_modules/**"
  - "frontend/**/*.d.ts"
  - "frontend/**/*.config.*"
  - "frontend/**/vitest-setup*.ts"
  - "frontend/src/app.html"
  - "docs/**"
  - "tests/**"
  - "**/*.test.*"
  - "**/*.spec.*"
