[project]
name = "satin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-settings>=2.10.1",
    "pymongo>=4.13.2",
    "strawberry-graphql[fastapi]>=0.278.0",
]

[project.scripts]
satin = "satin:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.17.0",
    "pytest>=8.4.1",
    "pytest-xdist>=3.8.0",
    "ruff>=0.12.5",
    "ssort>=0.15.0",
    "strawberry-graphql[cli]>=0.278.0",
]

###########
# Linting #
###########

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
ignore_missing_imports = true
check_untyped_defs = true
exclude = ["tests"]

[tool.ruff]
line-length = 120
target-version = "py312"
lint.select = [
  "ALL", # include all the rules, including new ones
]
lint.ignore = [
  "ANN",     # flake8-annotations
  "D100",    # ignore missing docs
  "D101",
  "D203",    # ignore no blank lines before class docstring
  "D213",    # multi-line docstring summary should start at the second line
  "COM812",  # ignore missing blank line after last section
  "FBT001",  # ignore boolean arguments
  "FBT002",
  "TD",      # ignore TODOs
  "FIX002",  # ignore TODOs
  "PLR0913", # ignore too many arguments
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = [
  "D104", # ignore missing docs
]
"tests/**/*.py" = [
  "D100",    # ignore missing docs
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D107",
  "ANN",     # flake8-annotations
  "S101",    # ignore asserts
  "PLR2004", # ignore magic values
  "PD901",   # allow df as variable name
  "SLF001",  # private method accessed outside of class
  "PGH003",  # allow unspecified type ignores
]
"docs/conf.py" = ["ALL"]
