version: '3.8'

services:
  # Development container
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro
    command: sleep infinity
    networks:
      - satin-dev-network
    environment:
      - ENVIRONMENT=development
      - MONGO_DSN=mongodb://admin:password@mongodb:27017/satin?authSource=admin
      - VITE_BACKEND_URL=http://localhost:8000
      - NODE_ENV=development
    depends_on:
      - mongodb

  # MongoDB database for development
  mongodb:
    image: mongo:7-jammy
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: satin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ../docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - satin-dev-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  satin-dev-network:
    driver: bridge

volumes:
  mongodb_dev_data:
    driver: local
  devcontainer-vscode-extensions:
  devcontainer-vscode-extensions-insiders:
