name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync --system --group dev
      - name: Lint with ruff
        run: ruff check .
      - name: Type check with mypy
        run: mypy src
      - name: Test with pytest
        run: pytest

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install
      - name: Lint and format check
        working-directory: ./frontend
        run: pnpm lint
      - name: Type check
        working-directory: ./frontend
        run: pnpm check
      - name: Test with vitest
        working-directory: ./frontend
        run: pnpm test
